apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: foobarapp:v1
    name: foo-bar-app
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
